### ISSUE TITLE
Facebook registration error

### ISSUE THREAD

**Issue by tikend** [Crowdex/crowdex.github.io#3]
Error registering via Facebook. Change attachment extension to html

[NoMethodError at _auth_facebook_callback.pdf](https://github.com/Crowdex/crowdex.github.io/files/77094/NoMethodError.at._auth_facebook_callback.pdf)

**Comment by petergaspar** [comment]
Prosim v buducnosti vytvaraj issues v tomto repozitare:
https://github.com/slavosarik/Crowdex
